extra_css:
  - style.css
markdown_extensions:
  - smarty
  - toc:
      permalink: true
nav:
  - NEWS.md
  - DOCKER.md
plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - style.css
  - search
site_author: AJ Slater
site_description: null
site_name: null
theme:
  color_mode: dark
  logo: img/logo.svg
  name: mkdocs
  strict: true
